import time
from selenium import webdriver
from selenium.webdriver.support.select import Select
from selenium.webdriver.common.by import By
from selenium.webdriver.support.wait import WebDriverWait
from selenium.webdriver.support import expected_conditions as EC

# ОТОБРАЖЕНИЕ СТРАНИЦЫ ТОВАРА
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# log_username = driver.find_element_by_id("username")
# log_username.send_keys("EVK@gmail.com")
# log_password = driver.find_element_by_id("password")
# log_password.send_keys("!!!MartiN!@#$%^&*()16081985!!!")
# time.sleep(3)
# login = driver.find_element_by_class_name("login>:nth-child(3)>:nth-child(3)")
# login.click()
# shop=driver.find_element_by_id("menu-item-40")
# shop.click()
# time.sleep(3)
# driver.execute_script("window.scrollBy(0, 400);")
# book=driver.find_element_by_class_name("post-181")
# book.click()
# book_name=driver.find_element_by_class_name("summary>:nth-child(1)")
# book_name_title = book_name.text
# assert "HTML5 Forms" in book_name_title
# print("Заголовок книги назвается: 'HTML5 Forms')
# driver.quit()

# КОЛИЧЕСТВО ТОВАРОВ В КАТЕГОРИИ
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# menu = driver.find_element_by_id("menu-item-50")
# menu.click()
# log_username = driver.find_element_by_id("username")
# log_username.send_keys("EVK@gmail.com")
# log_password = driver.find_element_by_id("password")
# log_password.send_keys("!!!MartiN!@#$%^&*()16081985!!!")
# time.sleep(3)
# login = driver.find_element_by_class_name("login>:nth-child(3)>:nth-child(3)")
# login.click()
# time.sleep(3)
# shop = driver.find_element_by_id("menu-item-40")
# shop.click()
# prod_cat = driver.find_element_by_xpath("//*[text()='HTML']")
# prod_cat.click()
# items_on_page = driver.find_elements_by_class_name("attachment-shop_catalog.size-shop_catalog.wp-post-image")
# time.sleep(5)
# print("На странице: " + str(len(items_on_page))+" товара")
# driver.quit()

# СОРТИРОВКА ТОВАРОВ
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# menu = driver.find_element_by_id("menu-item-50")
# menu.click()
# log_username = driver.find_element_by_id("username")
# log_username.send_keys("EVK@gmail.com")
# log_password = driver.find_element_by_id("password")
# log_password.send_keys("!!!MartiN!@#$%^&*()16081985!!!")
# time.sleep(3)
# login = driver.find_element_by_class_name("login>:nth-child(3)>:nth-child(3)")
# login.click()
# time.sleep(3)
# shop = driver.find_element_by_id("menu-item-40")
# shop.click()
# selector = driver.find_element_by_class_name("woocommerce-ordering .orderby")
# select = Select(selector)
# select.select_by_value("menu_order")
# assert "Default sorting" in selector.text
# print("Выбран вариант сортировки по умолчанию")
# select.select_by_value("price-desc")
# selector_price = driver.find_element_by_class_name("woocommerce-ordering .orderby")
# assert "Sort by price: high to low" in selector_price.text
# print("Выбран вариант сортировки по цене от большей к меньшей")
# driver.quit()

# # ОТОБРАЖЕНИЕ, СКИДКА ТОВАРА
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# menu = driver.find_element_by_id("menu-item-50")
# menu.click()
# log_username = driver.find_element_by_id("username")
# log_username.send_keys("EVK@gmail.com")
# log_password = driver.find_element_by_id("password")
# log_password.send_keys("!!!MartiN!@#$%^&*()16081985!!!")
# time.sleep(3)
# login = driver.find_element_by_class_name("login>:nth-child(3)>:nth-child(3)")
# login.click()
# time.sleep(3)
# shop = driver.find_element_by_id("menu-item-40")
# shop.click()
# driver.execute_script("window.scrollBy(0, 400);")
# time.sleep(3)
# book = driver.find_element_by_css_selector(".post-169>:nth-child(1)")
# book.click()
# old_price = driver.find_element_by_xpath("//span[contains(text(),'600')]")
# price_1=old_price.text
# assert "600" in price_1
# print("Старая цена книги 600")
# new_price = driver.find_element_by_xpath("//span[contains(text(),'450')]")
# price_2=new_price.text
# assert "450" in price_2
# print("Новая цена книги 450")
# image = WebDriverWait(driver, 5).until( EC.element_to_be_clickable((By.XPATH,"//div[@class='images']")) )
# image.click()
# close_image = WebDriverWait(driver, 5).until( EC.element_to_be_clickable((By.XPATH,"//a[@class='pp_close']")) )
# close_image.click()
# # driver.quit()

# ПРОВЕРКА ЦЕНЫ В КОРЗИНЕ
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# shop = driver.find_element_by_id("menu-item-40")
# shop.click()
# driver.execute_script("window.scrollBy(0, 600);")
# add_to_basket = driver.find_element_by_xpath("//a[@data-product_id='165']")
# add_to_basket.click()
# time.sleep(5)
# quantity = driver.find_element_by_xpath("//span[@class='cartcontents']")
# quantity_check = quantity.text
# time.sleep(5)
# assert "1 " in quantity_check
# price = driver.find_element_by_xpath("//span[@class='amount']")
# price_check = price.text
# assert "₹350.00" in price_check
# basket = driver.find_element_by_class_name("wpmenucart-icon-shopping-cart-0")
# basket.click()
# subtotal = WebDriverWait(driver, 5).until( EC.element_to_be_clickable((By.XPATH,"//td[@data-title='Subtotal']")) )
# subtotal_check = subtotal.text
# assert "350.00" in subtotal_check
# total = WebDriverWait(driver, 5).until( EC.element_to_be_clickable((By.CLASS_NAME,"order-total")) )
# total_check = total.text
# assert "357.00" in total_check
# driver.quit()

# РАБОТА В КОРЗИНЕ
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# shop = driver.find_element_by_id("menu-item-40")
# shop.click()
# driver.execute_script("window.scrollBy(0, 300);")
# add_to_basket = driver.find_element_by_xpath("//a[@data-product_id='165']")
# add_to_basket.click()
# time.sleep(5)
# basket = driver.find_element_by_class_name("wpmenucart-icon-shopping-cart-0")
# basket.click()
# time.sleep(5)
# delete_book = driver.find_element_by_xpath("//a[@title='Remove this item']")
# delete_book.click()
# time.sleep(5)
# undo_book = driver.find_element_by_xpath("//a[text() ='Undo?']")
# undo_book.click()
# quantity = driver.find_element_by_xpath("//input[@type='number']")
# quantity.clear()
# time.sleep(3)
# quantity.send_keys("3")
# update_basket = driver.find_element_by_xpath("//input[@value='Update Basket']")
# update_basket.click()
# time.sleep(3)
# selector= driver.find_element_by_xpath("//input[@type='number']")
# selector_get_value = selector.get_attribute("value")
# assert selector_get_value == "3"
# apply = driver.find_element_by_css_selector(".coupon .button")
# apply.click()
# time.sleep(3)
# coupon = driver.find_element_by_css_selector(".woocommerce-error>li")
# coupon_get_text = coupon.text
# assert "Please enter a coupon code" in coupon_get_text

# ПОКУПКА ТОВАРА
# driver = webdriver.Chrome(executable_path='C:/chromedriver.exe')
# driver.maximize_window()
# driver.get("http://practice.automationtesting.in/")
# shop = driver.find_element_by_id("menu-item-40")
# shop.click()
# driver.execute_script("window.scrollBy(0, 800);")
# time.sleep(3)
# add_to_basket = driver.find_element_by_css_selector(".post-165>:nth-child(2)")
# add_to_basket.click()
# time.sleep(3)
# basket = driver.find_element_by_class_name("wpmenucart-icon-shopping-cart-0")
# basket.click()
# proceed_to_checkout = WebDriverWait(driver, 5).until( EC.element_to_be_clickable((By.CSS_SELECTOR,".wc-proceed-to-checkout>a")) )
# proceed_to_checkout.click()
# first_name =  WebDriverWait(driver, 5).until( EC.element_to_be_clickable((By.ID,"billing_first_name")) )
# first_name.send_keys("Jared")
# last_name = driver.find_element_by_id("billing_last_name")
# last_name.send_keys("Leto")
# email = driver.find_element_by_id("billing_email")
# email.send_keys("mrleto@gmail.com")
# phone = driver.find_element_by_id("billing_phone")
# phone.send_keys("+79845632145")
# country = driver.find_element_by_id("s2id_billing_country")
# country.click()
# country_name = driver.find_element_by_id("s2id_autogen1_search")
# country_name.send_keys("Argentina")
# select_country_name = driver.find_element_by_class_name("select2-result-label")
# select_country_name.click()
# adress = driver.find_element_by_id("billing_address_1")
# adress.send_keys("Maradonna street,27")
# city = driver.find_element_by_id("billing_city")
# city.send_keys("Buenos Aires")
# state = driver.find_element_by_id("select2-chosen-2")
# state.click()
# state_name = driver.find_element_by_id("s2id_autogen2_search")
# state_name.click()
# select_state_name = driver.find_element_by_class_name("select2-results>:nth-child(2)")
# select_state_name.click()
# postcode = driver.find_element_by_xpath("//label[@for='billing_postcode']")
# postcode.click()
# postcode_name = driver.find_element_by_xpath("//input[@autocomplete='postal-code']")
# postcode_name.send_keys("123456789")
# driver.execute_script("window.scrollBy(0, 600);")
# time.sleep(3)
# payment_metod = driver.find_element_by_id("payment_method_cheque")
# payment_metod.click()
# place_order = driver.find_element_by_id("place_order")
# place_order.click()
# order_statys = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.CLASS_NAME, "woocommerce-thankyou-order-received"), "Thank you. Your order has been received."))
# payment_metod_status = WebDriverWait(driver, 10).until(EC.text_to_be_present_in_element((By.TAG_NAME, "tfoot>:nth-child(3)"), "Check Payments"))
# driver.quit()